export interface Job {
  OBJcity: string
  OBJcompanyDisplay: string
  OBJcompanyID: number
  OBJcountry: string
  OBJdesc: string
  OBJindustry: string
  OBJjobTags: [string]
  OBJpostingDate: string
  OBJstate: string
  OBJstateCode: string
  OBJtitle: string
  OBJtitleDisplay: string
  OBJurl: string
  OBJzipcode: string
  actionDateSince: string
  benefits: [string]
  bestCompaniesPageURLAtJobLocation: string
  careerMainPageURL: string
  companyCategories: [string]
  companyID: number
  companyInitial: string
  companyLogo: string
  companyName: string
  companyZippiaOverallScore: number
  contactEmails: []
  contactEmailsFlag: boolean
  cpc: number
  easyApplyFlag: boolean
  estimatedSalary: string
  formattedOriginalCompanyName: string
  iconClass: string
  iconSVG: string
  isSpammyCompany: boolean
  jobDescription: string
  jobId: string
  jobLevels: [string]
  jobMajor: boolean
  jobTags: [string]
  jobTitle: string
  jobURL: string
  listingHash: string
  location: string
  nearbyTo0: [string]
  originalCPC: string
  partnerName: string
  postedDate: string
  postingDate: string
  preferredDegrees: [string]
  requiredDegree: null
  showNewJobBedge: boolean
  skillsets: [string]
  snippets: [string]
  socCodeName: boolean
  socode: string
  source: string
  sponsorFlag: boolean
  sponsoredDlp: boolean
  templateName: string
  titleID: string
  unifiedZippiaSalary: number
  url: string
}
